baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '老有所养'
theme = 'ananke'
publishDir = 'docs'

hasCJKLanguage = true
summaryLength = 29

canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

